import React, { useState } from 'react';


const countries =[
    {"code":"BI","name":"Afghanistan"},
    {"code":"CV","name":"Åland Islands"},
    {"code":"KH","name":"Albania"},
    {"code":"CM","name":"Algeria"},
    {"code":"CA","name":"American Samoa"},
    {"code":"KY","name":"Andorra"},
    {"code":"CF","name":"Angola"},
    {"code":"TD","name":"Anguilla"},
    {"code":"CL","name":"Antarctica"},
    {"code":"CN","name":"Antigua and Barbuda"},
    {"code":"CX","name":"Argentina"},
    {"code":"CC","name":"Armenia"},
    {"code":"CO","name":"Aruba"},
    {"code":"KM","name":"Australia"},
    {"code":"CG","name":"Austria"},
    {"code":"CD","name":"Azerbaijan"},
    {"code":"CK","name":"Bahamas"},
    {"code":"CR","name":"Bahrain"},
    {"code":"CI","name":"Bangladesh"},
    {"code":"HR","name":"Barbados"},
    {"code":"CU","name":"Belarus"},
    {"code":"CW","name":"Belgium"},
    {"code":"CY","name":"Belize"},
    {"code":"CZ","name":"Benin"},
    {"code":"DK","name":"Bermuda"},
    {"code":"DJ","name":"Bhutan"},
    {"code":"DM","name":""},
    {"code":"DO","name":""},
    {"code":"EC","name":""},
    {"code":"EG","name":""},
    {"code":"SV","name":""},
    {"code":"GQ","name":""},
    {"code":"ER","name":""},
    {"code":"EE","name":""},
    {"code":"SZ","name":""},
    {"code":"ET","name":""},
    {"code":"FK","name":""},
    {"code":"FO","name":""},
    {"code":"FJ","name":""},
    {"code":"FI","name":""},
    {"code":"FR","name":""},
    {"code":"GF","name":""},
    {"code":"PF","name":""},
    {"code":"TF","name":""},
    {"code":"GA","name":""},
    {"code":"GM","name":""},
    {"code":"GE","name":""},
    {"code":"DE","name":""},
    {"code":"GH","name":""},
    {"code":"GI","name":""},
    {"code":"GR","name":""},
    {"code":"GL","name":""},
    {"code":"GD","name":""},
    {"code":"GP","name":""},
    {"code":"GU","name":""},
    {"code":"GT","name":""},
    {"code":"GG","name":""},
    {"code":"GN","name":""},
    {"code":"GW","name":""},
    {"code":"GY","name":""},
    {"code":"HT","name":""},
    {"code":"HM","name":""},
    {"code":"VA","name":""},
    {"code":"HN","name":""},
    {"code":"HK","name":""},
    {"code":"HU","name":""},
    {"code":"IS","name":""},
    {"code":"IN","name":""},
    {"code":"ID","name":""},
    {"code":"IR","name":""},
    {"code":"IQ","name":""},
    {"code":"IE","name":""},
    {"code":"IM","name":""},
    {"code":"IL","name":""},
    {"code":"IT","name":""},
    {"code":"JM","name":""},
    {"code":"JP","name":""},
    {"code":"JE","name":""},
    {"code":"JO","name":""},
    {"code":"KZ","name":""},
    {"code":"KE","name":""},
    {"code":"KI","name":""},
    {"code":"KP","name":""},
    {"code":"KR","name":""},
    {"code":"KW","name":""},
    {"code":"KG","name":""},
    {"code":"LA","name":""},
    {"code":"LV","name":""},
    {"code":"LB","name":""},
    {"code":"LS","name":""},
    {"code":"LR","name":""},
    {"code":"LY","name":""},
    {"code":"LI","name":""},
    {"code":"LT","name":""},
    {"code":"LU","name":""},
    {"code":"MO","name":""},
    {"code":"MG","name":""},
    {"code":"MW","name":""},
    {"code":"MY","name":""},
    {"code":"MV","name":""},
    {"code":"ML","name":""},
    {"code":"MT","name":""},
    {"code":"MH","name":""},
    {"code":"MQ","name":""},
    {"code":"MR","name":""},
    {"code":"MU","name":""},
    {"code":"YT","name":""},
    {"code":"MX","name":""},
    {"code":"FM","name":""},
    {"code":"MD","name":""},
    {"code":"MC","name":""},
    {"code":"MN","name":""},
    {"code":"ME","name":""},
    {"code":"MS","name":""},
    {"code":"MA","name":""},
    {"code":"MZ","name":""},
    {"code":"MM","name":""},
    {"code":"NA","name":""},
    {"code":"NR","name":""},
    {"code":"NP","name":""},
    {"code":"NL","name":""},
    {"code":"NC","name":""},
    {"code":"NZ","name":""},
    {"code":"NI","name":""},
    {"code":"NE","name":""},
    {"code":"NG","name":""},
    {"code":"NU","name":""},
    {"code":"NF","name":""},
    {"code":"MK","name":""},
    {"code":"MP","name":""},
    {"code":"NO","name":""},
    {"code":"OM","name":""},
    {"code":"PK","name":""},
    {"code":"PW","name":""},
    {"code":"PS","name":""},
    {"code":"PA","name":""},
    {"code":"PG","name":""},
    {"code":"PY","name":""},
    {"code":"PE","name":""},
    {"code":"PH","name":""},
    {"code":"PN","name":""},
    {"code":"PL","name":""},
    {"code":"PT","name":""},
    {"code":"PR","name":""},
    {"code":"QA","name":""},
    {"code":"RE","name":""},
    {"code":"RO","name":""},
    {"code":"RU","name":""},
    {"code":"RW","name":""},
    {"code":"BL","name":""},
    {"code":"SH","name":""},
    {"code":"KN","name":""},
    {"code":"LC","name":""},
    {"code":"MF","name":""},
    {"code":"PM","name":""},
    {"code":"VC","name":""},
    {"code":"WS","name":""},
    {"code":"SM","name":""},
    {"code":"ST","name":""},
    {"code":"SA","name":""},
    {"code":"SN","name":""},
    {"code":"RS","name":""},
    {"code":"SC","name":""},
    {"code":"SL","name":""},
    {"code":"SG","name":""},
    {"code":"SX","name":""},
    {"code":"SK","name":""},
    {"code":"SI","name":""},
    {"code":"SB","name":""},
    {"code":"SO","name":""},
    {"code":"ZA","name":""},
    {"code":"GS","name":""},
    {"code":"SS","name":""},
    {"code":"ES","name":""},
    {"code":"LK","name":""},
    {"code":"SD","name":""},
    {"code":"SR","name":""},
    {"code":"SJ","name":""},
    {"code":"SE","name":"Sweden"},
    {"code":"CH","name":"Switzerland"},
    {"code":"SY","name":"Syrian Arab Republic"},
    {"code":"TW","name":"Taiwan, Province of China"},
    {"code":"TJ","name":"Tajikistan"},
    {"code":"TZ","name":"Tanzania, United Republic of"},
    {"code":"TH","name":"Thailand"},
    {"code":"TL","name":"Timor-Leste"},
    {"code":"TG","name":"Togo"},
    {"code":"TK","name":"Tokelau"},
    {"code":"TO","name":"Tonga"},
    {"code":"TT","name":"Trinidad and Tobago"},
    {"code":"TN","name":"Tunisia"},
    {"code":"TR","name":"Turkey"},
    {"code":"TM","name":"Turkmenistan"},
    {"code":"TC","name":"Turks and Caicos Islands"},
    {"code":"TV","name":"Tuvalu"},
    {"code":"UG","name":"Uganda"},
    {"code":"UA","name":"Ukraine"},
    {"code":"AE","name":"United Arab Emirates"},
    {"code":"GB","name":"United Kingdom of Great Britain and Northern Ireland"},
    {"code":"US","name":"United States of America"},
    {"code":"UM","name":"United States Minor Outlying Islands"},
    {"code":"UY","name":"Uruguay"},
    {"code":"UZ","name":"Uzbekistan"},
    {"code":"VU","name":"Vanuatu"},
    {"code":"VE","name":"Venezuela (Bolivarian Republic of)"},
    {"code":"VN","name":"Viet Nam"},
    {"code":"VG","name":"Virgin Islands (British)"},
    {"code":"VI","name":"Virgin Islands (U.S.)"},
    {"code":"WF","name":"Wallis and Futuna"},
    {"code":"EH","name":"Western Sahara"},
    {"code":"YE","name":"Yemen"},
    {"code":"ZM","name":"Zambia"},
    {"code":"ZW","name":"Zimbabwe"},
    
];



export default function CountriesInput({  }) {
  return (
    <div className="mb-3 row">
      <label htmlFor="country" className="col-sm-3 col-form-label">Country</label>
      <div className="col-sm-9">
        <select
          name="country"
          id="country"
          defaultValue={"GB"}
          className="form-select"
        >
          {countries.map((country) => (
            <option key={country.code} value={country.code}>
              {country.name}
            </option>
          ))}
        </select>
      </div>
    </div>
  );
}


